#!/bin/bash

function changeProperty {
	sed -i 's@'"$1"'@'"$2"'@g' $JBOSS_HOME/domain/configuration/host.xml
}

PASSWORD=`echo -n $MASTER_ENV_MASTER_PASSWORD | base64`

changeProperty "MASTER_PASSWORD" "$PASSWORD"
changeProperty "SLAVE_HOST_NAME" "$SLAVE_HOST_NAME"
changeProperty "MASTER_SERVER_PORT" "$MASTER_PORT_9999_TCP_PORT"
changeProperty "MASTER_SERVER_NAME" "$MASTER_PORT_9999_TCP_ADDR"
changeProperty "SLAVE_SERVER_NAME" "$SLAVE_SERVER_NAME"
changeProperty "SERVER_GROUP" "$SERVER_GROUP"

$JBOSS_HOME/bin/domain.sh -Djboss.domain.master.address=$MASTER_PORT_9999_TCP_ADDR -b 0.0.0.0 -bmanagement 0.0.0.0 
